### ISSUE TITLE
Web Managing Page

### ISSUE THREAD

**Issue by huseyinergen** [pihomeserver/Kupiki-Hotspot-Script#61]
Hi everybody.. i installed (i used full image on this page) i logged pi/raspbian in cli. 

But i can not access via web page from another pc. What i make for this ? Please more explain how works this system

**Comment by pihomeserver** [comment]
Please also explained what you made : did you create a user within daloradius ? did you log into the hotspot ? was the authentication solved ? 

Also i have to kick that full image that is using a so old release of the hotspot

**Comment by huseyinergen** [comment]
i want login and manage hotspot. is there any web management page ? for example http://10.0.1.25/daloradius

**Comment by pihomeserver** [comment]
No there is not for now (It's in progress and in testing) You have to either customize parameters of scripts (see first lines and README) to customize your SSID etc and use daloradius for users management
Once installed if you want to update the configuration you have to change configuration files manually.

The web interface release will help you to manage all configuration (including user management) in one place. But it will not be released within next weeks

**Comment by morningstar74** [comment]
Hello.. Thanks for image.. I used full image install and i got same problem.. Can't login in hotspot..
I Haven't change anything in script.. I just want to login and idk user and password for login..

**Comment by pihomeserver** [comment]
You have to use daloradius to create your users accounts. It's in the readme
-------- Message d'origine --------De : morningstar74 <notifications@github.com> Date : 05/10/2017  07:03  (GMT+01:00) À : pihomeserver/Kupiki-Hotspot-Script <Kupiki-Hotspot-Script@noreply.github.com> Cc : Pi Home Server <pihomeserver@gmail.com>, Comment <comment@noreply.github.com> Objet : Re: [pihomeserver/Kupiki-Hotspot-Script] Web Managing Page (#61) 
Hello.. Thanks for image.. I used full image install and i got same problem.. Can't login in hotspot..

I Haven't change anything in script.. I just want to login and idk user and password for login..

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pihomeserver/Kupiki-Hotspot-Script","title":"pihomeserver/Kupiki-Hotspot-Script","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pihomeserver/Kupiki-Hotspot-Script"}},"updates":{"snippets":[{"icon":"PERSON","message":"@morningstar74 in #61: Hello.. Thanks for image.. I used full image install and i got same problem.. Can't login in hotspot..\r\nI Haven't change anything in script.. I just want to login and idk user and password for login.. "}],"action":{"name":"View Issue","url":"https://github.com/pihomeserver/Kupiki-Hotspot-Script/issues/61#issuecomment-334360058"}}}
