### ISSUE TITLE
Error on script run: "Could not resolve host: github.com"

### ISSUE THREAD

**Issue by AdrianMrn** [pihomeserver/Kupiki-Hotspot-Script#71]
Heya!

I'm installing the script on the latest version of Raspbian Lite and halfway through the installation, when the script is running `Cloning CoovaChilli project`, I get the error `fatal: unable to access 'https://github.com/coova/coova-chilli.git/': Could not resolve host: github.com`.

This is right after the script runs `Restarting networking (via systemctl): networking.service.`

I saw some other people had this same issue, is there a fix? Or am I doing something wrong? :)

Thanks

EDIT:
I imagine this is happening because my network controller on the rpi is being reset, changing the IP address etc. Problem is I'm using the wlan0 NIC to access the internet, but I also want to host the hotspot on that NIC. I realise it isn't possible to have both of them on the same controller, but I currently don't have access to internet through ethernet cable. I wasn't going to use the hotspot to connect the client to the internet, just to the rpi's network.

**Comment by pihomeserver** [comment]
Hello
You found the reason yourself. You can't use same NIC for hotspot and internet at the same time.
Also there is a generated iptable in the coova up.sh script that blocks all traffic on the api network for security reason.

Try to connect your ethernet NIC while installing the script and then update up.sh to remove the iptable rule. Keep in mind how you will be able to ssh your pi or update it ...

**Comment by reigelgallarde** [comment]
Yes, I can confirm this is happening... it's because of the line where you will run a network restart and then without even finishing restart, the script calls for a git clone.

My workaround was to run the cloning first, then restart network, then continue with the rest...
In short, I move `Cloning CoovaChilli project` above `Restarting networking (via systemctl): networking.service.`

**Comment by reigelgallarde** [comment]
It might be a good idea to create another function that clones or downloads the needed source files after installing the dependent packages.

Something like `download_source_files() { }`...
Then this will be called next to https://github.com/pihomeserver/Kupiki-Hotspot-Script/blob/master/pihotspot.sh#L342
````
install_dependent_packages PIHOTSPOT_DEPS[@]
download_source_files
````

**Comment by pihomeserver** [comment]
@reigelgallarde thanks for the tip. I will work on that. Maybe this should be done at the end of the script to allow those who don't want to keep ethernet NIC to install the script.

**Comment by AdrianMrn** [comment]
Thanks for the fast and incredibly helpful feedback, guys :)

I'll see if I can find some time to create a pull request

**Comment by reigelgallarde** [comment]
@pihomeserver , what I meant was move all the lines that does all the cloning and downloading of source files... move it inside `download_source_files`

so at the very least, after these two functions, internet connection is not required... it will fixed this issue #71.

```
install_dependent_packages PIHOTSPOT_DEPS[@]
download_source_files
```

**Comment by pihomeserver** [comment]
@AdrianMrn the script has been updated. You can give a try to it and tell us if it does what you were expecting

**Comment by reigelgallarde** [comment]
I have tried the script and it works...

although, I'm not sure why but my pi can't get past this line
`execute_command "/etc/init.d/networking restart" true "Restarting network service to take IP forwarding into account"`

My pi would loss my connection because I'm on ssh..
So, when I'm on ssh, I just remove that line and do manual reboot after the script is done...
Just a note for everyone...

**Comment by pihomeserver** [comment]
Last versions of the script perform well from start to end. Reopen if same issue still persists
